#!/bin/bash

wget https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2013-01.csv
wget https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2013-02.csv
wget https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2013-03.csv
wget https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2013-04.csv
wget https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2013-05.csv
wget https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2013-06.csv
wget https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2013-07.csv
wget https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2013-08.csv
wget https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2013-09.csv
wget https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2013-10.csv
wget https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2013-11.csv
wget https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2013-12.csv
wget https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2014-01.csv
wget https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2014-02.csv
wget https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2014-03.csv
wget https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2014-04.csv
wget https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2014-05.csv
wget https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2014-06.csv
wget https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2014-07.csv
wget https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2014-08.csv
wget https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2014-09.csv
wget https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2014-10.csv
wget https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2014-11.csv
wget https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2014-12.csv
wget https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2015-01.csv
wget https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2015-02.csv
wget https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2015-03.csv
wget https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2015-04.csv
wget https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2015-05.csv
wget https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2015-06.csv
wget https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2015-07.csv
wget https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2015-08.csv
wget https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2015-09.csv
wget https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2015-10.csv
wget https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2015-11.csv
wget https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2015-12.csv
wget https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2016-01.csv
wget https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2016-02.csv
wget https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2016-03.csv
wget https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2016-04.csv
wget https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2016-05.csv
wget https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2016-06.csv
